package com.example.demo.entity;

public class Usercart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercart.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercart.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercart.product_price
     *
     * @mbggenerated
     */
    private Integer productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercart.product_nunber
     *
     * @mbggenerated
     */
    private Integer productNunber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercart.product_src
     *
     * @mbggenerated
     */
    private String productSrc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercart.product_id
     *
     * @return the value of usercart.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercart.product_id
     *
     * @param productId the value for usercart.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercart.product_name
     *
     * @return the value of usercart.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercart.product_name
     *
     * @param productName the value for usercart.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercart.product_price
     *
     * @return the value of usercart.product_price
     *
     * @mbggenerated
     */
    public Integer getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercart.product_price
     *
     * @param productPrice the value for usercart.product_price
     *
     * @mbggenerated
     */
    public void setProductPrice(Integer productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercart.product_nunber
     *
     * @return the value of usercart.product_nunber
     *
     * @mbggenerated
     */
    public Integer getProductNunber() {
        return productNunber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercart.product_nunber
     *
     * @param productNunber the value for usercart.product_nunber
     *
     * @mbggenerated
     */
    public void setProductNunber(Integer productNunber) {
        this.productNunber = productNunber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercart.product_src
     *
     * @return the value of usercart.product_src
     *
     * @mbggenerated
     */
    public String getProductSrc() {
        return productSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercart.product_src
     *
     * @param productSrc the value for usercart.product_src
     *
     * @mbggenerated
     */
    public void setProductSrc(String productSrc) {
        this.productSrc = productSrc == null ? null : productSrc.trim();
    }
}