package com.example.demo.mapper;

import com.example.demo.entity.Usercart;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;


@Mapper
@Component
public interface UsercartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercart
     *
     * @mbggenerated
     */
    int insert(Usercart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercart
     *
     * @mbggenerated
     */
    int insertSelective(Usercart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercart
     *
     * @mbggenerated
     */
    Usercart selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercart
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Usercart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Usercart record);

    ArrayList<Usercart> selectAll();
}